csvs/urls.py
from django.conf.urls import url
from django.urls import path
from .views import handle
from . import views

app_name = 'csvs'

urlpatterns = [
    path('', handle, name='upload-view'),
    url(r'^about/$', views.aboutview.as_view(), name='upload'),
]

upload_csv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('csvs.urls', namespace='csvs')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csvs/models.py
from django.db import models


class Csv(models.Model):
    file_name = models.FileField(upload_to='csvs')
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f"File id: {self.id}"

sales/models.py
from django.db import models


class Sale(models.Model):
    PLZ = models.TextField()
    Summe = models.TextField()

csvs/forms.py
from django import forms
from .models import Csv

class CsvModelForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name',)

csvs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django_tables2 import SingleTableView

from .forms import CsvModelForm
from .models import Csv
import csv

from sales.models import Sale
from sales.tables import PersonTable


def handle(request, *args, **options):
    form = CsvModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvModelForm()
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, "r") as f_in:
            data = csv.reader(f_in)

            for i, row in enumerate(data):
                if i == 0:
                    pass
                else:
                    Sale.objects.create(
                        PLZ=row[17],
                        Summe=row[6],
                    )

            obj.activated = True
            obj.save()

    return render(request, 'csvs/upload.html', {'form': form})


class AboutView(TemplateView):
    template_name = 'about.html'


class aboutview(SingleTableView):
    model = Sale
    table_class = PersonTable
    template_name = 'people.html'

sales/views.py
from django.shortcuts import render

# Create your views here.

csvs/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Test Project</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        {# MEDIUM STYLE EDITOR#}
        <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


        {# Custom CSS#}
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

        {# Fonts#}
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

<body class='loader'>

  <nav class="navbar navbar-default techfont custom-navbar">
    <div class="container">

      <ul class="nav navbar-nav">
          <li><a class='navbar-brand bigbrand' href="{% url 'csvs:upload-view' %}">Import</a></li>

        <li><a href="{% url 'csvs:upload'%}">Export</a></li>
        <li><a href="https://github.com/YuliiaAntonova/Django-CSV-File-Upload-main-3">Github</a></li>
        <li><a href="https://www.linkedin.com">LinkedIn</a></li>

      </ul>


  </div>
</nav>

  {# The actual blog posts#}
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                  <div class="blog_posts">
                    {% block content %}
                    {% endblock %}

                  </div>

                </div>
            </div>
        </div>

{# SCRIPTS#}

<script type="text/javascript" src="{% static 'js/blog.js' %}"></script>

</body>
</html>

csvs/templates/csvs/about.html
{% extends "base.html" %}
{% block content %}
<h1>About me</h1>
<p>Thanks for visiting my blog! Check all this cool stuff about me!</p>

{% endblock %}

csvs/templates/csvs/upload.html
{% extends 'base.html' %}

{% block title %}
Main Page
{% endblock title %}

{% block content %}
<form action="" method="POST" class="ui form" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{ form }}
    <button type= "submit" class="ui button primary">Confirm</button>
</form>
{% endblock content %}

csvs/templates/display.html
<!-- At the top of your page add load static -->
{% load static %}

<!-- In the body of the HTML page add this and continue adding all Fields. I have provided three example below -->
 <h1 class='list'>List View</h1>

       {% for k in data  %}
        <table border="1">

            <tr>
                <td>{{k.no}}</td>
                <td>{{k.product}}</td>
                <td>{{k.quantity}}</td>
                <td>{{k.salesman}}</td>

            </tr>

            {% endfor %}
        </table>

csvs/templates/people.html
{# tutorial/templates/tutorial/people.html #}
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>List of persons</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
        {% render_table table %}
    </body>
</html>